# -*- conf -*-

font=JetBrainsMono Nerd Font:size=11
font-bold=JetBrainsMono Nerd Font:bold:size=11
font-italic=JetBrainsMono Nerd Font:italic:size=11
font-bold-italic=JetBrainsMono Nerd Font:bold:italic:size=11

initial-window-size-pixels=850x520
pad=15x15 center

[scrollback]
lines=5000

[cursor]
style=beam
blink=yes
beam-thickness=1.5

[mouse]
hide-when-typing=yes

[colors-dark]
alpha=0.90
background=1e1e2e
foreground=cdd6f4
flash=7f7f00
flash-alpha=0.5

regular0=45475a  # black
regular1=f38ba8  # red
regular2=a6e3a1  # green
regular3=f9e2af  # yellow
regular4=89b4fa  # blue
regular5=f5c2e7  # magenta
regular6=94e2d5  # cyan
regular7=bac2de  # white

bright0=585b70   # bright black
bright1=f38ba8   # bright red
bright2=a6e3a1   # bright green
bright3=f9e2af   # bright yellow
bright4=89b4fa   # bright blue
bright5=f5c2e7   # bright magenta
bright6=94e2d5   # bright cyan
bright7=a6adc8   # bright white

selection-foreground=1e1e2e
selection-background=f5e0dc
urls=89b4fa

[csd]
preferred=none

[key-bindings]
clipboard-copy=Control+Shift+c XF86Copy
clipboard-paste=Control+Shift+v XF86Paste
search-start=Control+Shift+r
font-increase=Control+plus Control+equal Control+KP_Add
font-decrease=Control+minus Control+KP_Subtract
font-reset=Control+0 Control+KP_0
spawn-terminal=Control+Shift+n
show-urls-launch=Control+Shift+o
